### ISSUE TITLE
udp loss is always 0.0%

### ISSUE THREAD

**Issue by leark1** [wxiaoguang/echoping#1]
I use tc netem to create a 10% loss
```
# tc qdisc ls dev eth1
qdisc netem 8047: root refcnt 2 limit 100000 loss 10%
```

echoping client log like this 
```
 (20221028-200914.415871): pps=50.2, loss=0.0%, round-trip time (ms): avg=1.6, min=1.4, max=3.3, stddev=0.3, p90=1.8
 (20221028-200914.415871): pps=50.4, loss=0.0%, round-trip time (ms): avg=1.7, min=1.4, max=2.0, stddev=0.1, p90=1.9
 (20221028-200914.415871): pps=50.5, loss=0.0%, round-trip time (ms): avg=1.7, min=1.6, max=2.7, stddev=0.2, p90=1.9
```

server side
```
 (20221028-200914.415871): pps=44.0, tmperr=0
 (20221028-200914.415871): pps=44.0, tmperr=0
(20221028-200914.415871): pps=45.0, tmperr=0
```

according to pps (client 50 vs server 45), 10% loss is real, but client log always say loss=0.0%
iperf3 -u get 10% loss correctly

**Comment by wxiaoguang** [comment]
Thank you for the bug report. I think the bug was caused by an incorrect type-cast.

The fix is https://github.com/wxiaoguang/echoping/commit/ccb076e4c76a576875f4c65efa3a93df1970a437

(https://github.com/wxiaoguang/echoping/commit/ccb076e4c76a576875f4c65efa3a93df1970a437#diff-06d95ff0dbe602e236c84874bbecc61f36fbc4d462c75985e210ab1183d2e707R94)

The new release is  0.1.1: https://github.com/wxiaoguang/echoping/releases

**Comment by wxiaoguang** [comment]
I think the bug should have been fixed.

Feel free to re-open if there is still anything wrong.
